version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: VRustratie_app
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - VRustratie_network

  web:
    image: nginx:alpine
    container_name: VRustratie_web
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - VRustratie_network
    ports:
      - "8080:80"

  db:
    image: postgres:13
    container_name: VRustratie_db
    environment:
      POSTGRES_DB: VRustratie
      POSTGRES_USER: VRustratie
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata_VRustratie:/var/lib/postgresql/data
    networks:
      - VRustratie_network

networks:
  VRustratie_network:
    driver: bridge

volumes:
  pgdata_VRustratie: