@extends('layouts.admin')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">Manage Access Codes</div>

                    <div class="card-body">
                        <a href="{{ route('admin.codes.create') }}" class="btn btn-primary mb-3">Generate New Access Code</a>

                        @if(session('success'))
                            <div class="alert alert-success">
                                {{ session('success') }}
                            </div>
                        @endif

                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th>Code</th>
                                    <th>Playlist</th>
                                    <th>Generated By</th>
                                    <th>Status</th>
                                    <th>Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                @forelse($codes as $code)
                                    <tr>
                                        <td>{{ $code->code }}</td>
                                        <td>{{ $code->playlist->title }}</td>
                                        <td>{{ $code->generator->name }}</td>
                                        <td>{{ $code->is_active ? 'Active' : 'Inactive' }}</td>
                                        <td>
                                            <form action="{{ route('admin.codes.destroy', $code->id) }}" method="POST" style="display:inline-block;">
                                                @csrf
                                                @method('DELETE')
                                                <button type="submit" class="btn btn-sm btn-danger">Delete</button>
                                            </form>
                                        </td>
                                    </tr>
                                @empty
                                    <tr>
                                        <td colspan="5" class="text-center">No access codes found.</td>
                                    </tr>
                                @endforelse
                            </tbody>
                        </table>

                        {{ $codes->links() }} <!-- Pagination links -->
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection